db/names.sql

This commit adds two tables and all the functions for creating display
names.
```sql
SELECT *, f_display_name(reference_designator) FROM instrumentdeployments;
```

Adds database entries and functions

---

ooiservices/app/__init__.py
ooiservices/app/config.yml
ooiservices/app/main/__init__.py
ooiservices/app/main/authentication.py
ooiservices/app/main/errors.py
ooiservices/app/main/operator_event.py
ooiservices/app/main/routes.py
ooiservices/app/main/sys.py
ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/manage.py

- relative imports are plague to ambiguity and module clashing.
I would much rather NOT spend my weekends debugging behavior resulting
from relative imports.

Fixes the relative imports

---

ooiservices/app/config.yml
ooiservices/app/main/routes.py
ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/manage.py
ooiservices/tests/test_user.py

Adds USER ROLE support

---

ooiservices/requirements/common.txt
ooiservices/requirements/dev.txt

Allows us to parse ISO8601s very easily

Adds dependency python-dateutil

---

ooiservices/app/main/routes.py
ooiservices/app/models.py
ooiservices/requirements/common.txt

Adds route /platformlocation?reference_designator=

Adds hybrid property geojson to PlatformDeployments

---

ooiservices/app/models.py

This is an emergency fix as the to_json calls were failing.

Fixes to_json geo_location conversion in models.

---

README.md
ooiservices/app/models.py

See http://geoalchemy-2.readthedocs.org/en/latest/types.html
management=True is important
Updates README, adds routes.

Adds Geometry column opts to support PostGIS field creation.

---

ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/manage.py
ooiservices/requirements/common.txt
ooiservices/tests/test_user.py

@oceanzus , @lukecampbell 
A bit to insert the user scopes to be checked on by the UserScopeLink class

Mc user management

---

ooiservices/app/decorators.py
ooiservices/app/main/authentication.py
ooiservices/app/models.py
ooiservices/manage.py

@oceanzus , @lukecampbell 
Finished up the @scope_required decorator.
You’ll need to ensure the scopes are loaded, we need to work out how to add users to scopes through the UI and it’s route at some point.

finished @scope_required decorator

---

ooiservices/app/main/routes.py
ooiservices/tests/sampleData.json

update and add services for generating chart data

adds sample data for the services and generation of chart data

---

ooiservices/app/__init__.py
ooiservices/app/main/__init__.py
ooiservices/app/main/routes.py
ooiservices/app/redmine/__init__.py
ooiservices/app/uframe/__init__.py
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

Effort to organize, note the uframe prefix!
so, your proxy route would need to be updated from : ‘/get_data’ to ‘/uframe/get_data’

moved uframe routes to uframe blueprints, as well as helper methods.

---

ooiservices/app/uframe/controller.py
ooiservices/tests/test_uframe_data.py

add annotation support for UI plotting, dont merge yet as i want to add some tests.

add simple example of data annotation

---

ooiservices/app/models.py

x's and y's

---

ooiservices/app/uframe/controller.py

return stored annotations along side data response

Fix annotations dict

---

ooiservices/app/uframe/controller.py

forgot to init the annotations for things that dont require annotations

---

ooiservices/app/decorators.py
ooiservices/app/models.py
ooiservices/tests/test_annotations.py

- The columns specified in the model code, didn't actually exist.
Implemented a many-to-many relationship thru SQLAlchemy

Fixes scope issues

---

ooiservices/app/main/authentication.py
ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/tests/test_models.py

- Accounts can only be accessed that are enabled

Adds PUT /user and Checks active field for auth

---

.travis.yml
ooiservices/app/config.yml
ooiservices/app/redmine/__init__.py
ooiservices/app/redmine/routes.py
ooiservices/requirements/dev.txt
ooiservices/tests/test_redmine_api.py

@lukecampbell Please review/merge
A redmine account was made for UI testing purposes - OOI_UI_User. I have the redmine api key for this user. Need to update config.yml with this key for the tests to pass.

Redmine api

---

ooiservices/app/uframe/controller.py

- What's actually slow is the response. So if we memoize it we can
speed up our processing of the response.
- This allows us to execute multiple requests with query parameters AND
cache the response at the same time.
- I changed the response format to match the rest of the other services
responses

Updates the caches in the stream list

---

ooiservices/app/__init__.py
ooiservices/app/config.yml
ooiservices/app/main/__init__.py
ooiservices/app/main/instrument_deployment.py
ooiservices/app/main/routes.py

@lukecampbell , 
SSL protection implemented, usage for production.
CSRF protection from Flask-WTF implemented in app factory.
Refactor instrument_deployments to a permaent home (now that it is an awesome CRUD)!

Mc security

---

ooiservices/app/uframe/controller.py

@lukecampbell @FBRTMaka adds field to the request so we dont return all the data to the ui

update the services to allow for a field to be returned

---

ooiservices/app/main/errors.py
ooiservices/app/uframe/controller.py

@Luke, @birdage , @brian-smith723 
MORE LOGS!

Mc roundup

---

ooiservices/app/config.yml

@birdage 
Disable CSRF for development.

disable CSRF for development

---

ooiservices/app/main/annotation.py
ooiservices/app/uframe/controller.py

@lukecampbell fixes the annotation creation

fix annotations creation and request

---

ooiservices/app/redmine/routes.py
ooiservices/tests/test_redmine_api.py

@lukecampbell @dlangston 
Check out the wiki for details: https://github.com/asascience-open/ooi-ui-services/wiki/API-Redmine-Integration
Tests skip in Travis but are all passing on my machine

Add redmine endpoint to GET all users in a Redmine project

---

ooiservices/app/uframe/controller.py

Added the ability to download a csv of a data stream.  No itme bounds.

---

ooiservices/app/uframe/controller.py

Download CSV now writes to buffer.  Added JSON download option.

---

ooiservices/app/uframe/controller.py

NetCDF3 Download Capability

---

ooiservices/app/redmine/routes.py
ooiservices/tests/test_redmine_api.py

Also updates the POST endpoints to include all possible ticket fields
@lukecampbell @FBRTMaka please review/merge

Add scope and basic authentication

---

.gitignore
db/ooiui_schema_data.sql
ooiservices/app/models.py
ooiservices/manage.py
ooiservices/tests/test_annotations.py
ooiservices/tests/test_operator_event.py
ooiservices/tests/test_selenium.py
ooiservices/tests/test_user.py

Separates deployment methods.

---

ooiservices/app/uframe/controller.py

Changed Content Type for CSV and JSON

---

ooiservices/app/main/sys.py

remove shutdown endpoint

---

ooiservices/app/config.yml
ooiservices/app/uframe/controller.py

adds depth profile algorithm to uframe.py.

Depth profile

---

ooiservices/app/main/routes.py
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py
ooiservices/app/uframe/plotting.py
ooiservices/tests/test_uframe_data.py

fix plotting services

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py
ooiservices/app/uframe/plotting.py

add capability for profile plotting

Add profile plot

---

ooiservices/app/uframe/assetController.py
ooiservices/requirements/common.txt

@DanielJMaher 
Conversion for Lat/Lon support, only from uframe for now.  POST and PUT conversion to uframe on the way.

Mc uframe assets controller

---

ooiservices/app/uframe/assetController.py

More asset work!

---

ooiservices/app/uframe/assetController.py

Last addition to assets

---

ooiservices/app/uframe/assetController.py

formats for events POST/PUT

---

ooiservices/app/uframe/controller.py
ooiservices/requirements/common.txt

Add a glider track endpoint to services to fetch GeoJSON.
Also improved PEP8 compliance for a number of functions called by the route.

Adds glider tracks endpoint to uFrame controller

---

ooiservices/app/uframe/assetController.py

@DanielJMaher , 
Better comments for documentation.

Better inline comments for assets/events

---

ooiservices/app/__init__.py
ooiservices/app/uframe/assetController.py
ooiservices/requirements/common.txt

@DanielJMaher , @birdage , @brian-smith723 , @benjwadams , @dlangston 
Here is a possible fix to having the python UI proxy to the services.  Dan and I tested out a first pass and it was promising.  Would like to also try POST/PUT/DELETE.
@DanielJMaher , this will save a lot of time and headache of putting in a new proxy route for each of the services endpoint.  Is backwards compatible.

Mc cors fix

---

ooiservices/app/config.yml
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py
ooiservices/app/uframe/plotting.py
ooiservices/requirements/common.txt

@birdage this uses your pull request
asascience-open/ooi-ui#268
@DanielJMaher FYI

Implement multiple yaxis plots

---

ooiservices/app/uframe/controller.py
ooiservices/requirements/common.txt

The GEOS shared libraries can be problematic at best.

Replaces Shapely with python-geojson to avoid deployment issues.

---

ooiservices/app/uframe/controller.py

fixes glider track services issues

update glider track controller

---

ooiservices/app/uframe/controller.py

add metadata uframe connection

---

.gitignore
ooiservices/app/__init__.py

@birdage here you go andy!
just duplicate your config.yml file and call it "config_local.yml" and it'll read from that.

Local config file

---

ooiservices/app/config.yml
ooiservices/app/uframe/__init__.py
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

@DanielJMaher @oceanzus important fix

update uframe controller with metdata fixes

---

ooiservices/app/uframe/controller.py

Adds error handling for non-200 response from uFrame.

Fixes config variable conversion.

---

db/ooiui_schema_data.sql
ooiservices/app/config.yml
ooiservices/app/main/__init__.py
ooiservices/app/main/alertsalarms.py
ooiservices/app/models.py
ooiservices/app/uframe/controller.py
ooiservices/manage.py
ooiservices/tests/test_alert_alarm.py
ooiservices/tests/test_annotations.py

Adds data model and routes to support alerts and alarms.

---

ooiservices/app/uframe/assetController.py

@DanielJMaher , @oceanzus 
I know there is a code freeze, and this isn't critical but I just wanted to put it here so it didn't get lost.
This will GREATLY improve the performance of load times.

Cache Fix for Asset/Event listing

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py
ooiservices/app/uframe/plotting.py

fixes the variable access from the services to the ui for use with https://github.com/asascience-open/ooi-ui/pull/288
<b>Do Not Merge Yet</b>

add simple vars

---

ooiservices/app/config.yml
ooiservices/requirements/common.txt
ooiservices/requirements/dev.txt

Adds selenium and simplejson requirements.

Adds minor updates to config.

---

ooiservices/app/uframe/controller.py

Fixes UFRAME_DATA_REQUEST_LIMIT type conversion.

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

add time and size bounds

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py
ooiservices/app/uframe/plot_tools.py
ooiservices/app/uframe/plotting.py

Plotting cleanup

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/plot_tools.py
ooiservices/app/uframe/plotting.py

@birdage heads up
@DanielJMaher Work in progress, DONT merge yet

Plot updates

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

Update to services

---

ooiservices/app/config.yml
ooiservices/app/models.py
ooiservices/app/uframe/controller.py

DO NOT MERGE 
related to https://github.com/asascience-open/ooi-ui/pull/323

add toc controller route with small cache

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/plot_tools.py

DO NOT MERGE
fixes the platform/mooring code issue as well as adding a structured toc link

add structured toc link

---

ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/plot_tools.py

@DanielJMaher , @Bobfrat 
Bob, may need to go over with you to make sure that the event overlay on the plot working right.

support for event table list in plotting page

---

ooiservices/app/uframe/assetController.py

Fixes to Event loading on plotting page

---

ooiservices/app/uframe/controller.py

update download link for the ui download

---

ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/controller.py

@DanielJMaher backend for data catalog pagination/search enhancements

Mc stream pagination

---

ooiservices/app/uframe/controller.py

@DanielJMaher , not a big deal but just something I noticed that would need to be implemented.

Data catalog performance boost, and search is now case insensitive.

---

ooiservices/app/main/authentication.py

In progress - support for UI session management changes.

Sets the token to a full day.  Used in conjunction with UI timout update

---

ooiservices/app/main/c2.py

Platform dashboard status changes.

C2 changes for platform status processing.

---

ooiservices/app/main/c2.py
ooiservices/app/main/c2_mission.py
ooiservices/app/models.py
ooiservices/tests/test_c2.py
ooiservices/tests/test_user.py

CC permissions updates - DB REBUILD REQUIRED

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/plotting.py

fixes the profile data request

fix profile data access

---

ooiservices/app/uframe/controller.py

access the data via chunked parameter request

get profile data using parameter ids

---

ooiservices/app/uframe/controller.py

@DanielJMaher fixes the platform selection issue

fix the platform naming issue

---

ooiservices/app/uframe/assetController.py

@Bobfrat , @birdage , if you have a moment, please take a peak at the clean up of the assets GET endpoint and let me know if removing any of those keys will mess up your stuff.
I checked around a lot, and didn't see that it would - but I'd feel better if you had a look.
@DanielJMaher , This is to support all that AM work for the UI.

AM rest services update

---

ooiservices/app/uframe/assetController.py

@DanielJMaher 
If there is no response, this will error out nicely.

fixes bug when a asset is created poorly, a crummy error message appears

---

ooiservices/app/uframe/assetController.py

@DanielJMaher , also improves searching on assets as well as increases the cache timeout for the assets and events.

Support for Lat/Lon translation from events to assets.

---

ooiservices/app/uframe/assetController.py

@DanielJMaher this will grab the lat lon from the events when available.

Lat/Lon asset/event association

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py
ooiservices/app/uframe/plot_tools.py
ooiservices/app/uframe/plotting.py

@DanielJMaher this goes with https://github.com/asascience-open/ooi-ui/pull/368

Add time series QAQC plotting

---

ooiservices/app/uframe/controller.py

@Bobfrat Can you make sure I'm not crazy?  this is for uframe-dev only.

changes stream terminator again.

---

ooiservices/app/uframe/assetController.py

asset creating stability improvements

---

ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/controller.py

@DanielJMaher 
You may want to check your google analytics creation here, it's causing a ruckus! lol

better error handling when google analytics key is not valid

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

DO NOT MERGE YET, related to a UI PR coming soon

update data services

---

ooiservices/app/uframe/plotting.py

@birdage @DanielJMaher 
real simple fix, just messing with the dynamically generated label sizes

Adjust size of labels

---

ooiservices/app/uframe/controller.py

Add ability to download provenance and annotations for netcdf and json.
@birdage @DanielJMaher 
Don't merge, there's some ooi-ui code to go with this

Download provenance and annotations

---

ooiservices/app/uframe/controller.py

@birdage @DanielJMaher bug fix

Fix bug in csv download

---

ooiservices/app/config.yml
ooiservices/app/main/annotation.py
ooiservices/tests/test_annotations.py

update annotation processing

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/plot_tools.py
ooiservices/app/uframe/plotting.py

@birdage @DanielJMaher 
This checks for long titles and breaks it into 2 lines, makes sure quiver plots start and end at requested times, and adds a try catch to generating plots to prevent the whole stack being returned to the UI

Fix quiver start-end, error checking, title

---

ooiservices/app/uframe/assetController.py

@DanielJMaher , @birdage Please review logic on variables being reset in loops.

Resets variables properly

---

ooiservices/app/main/routes.py

Glider trick

---

ooiservices/app/uframe/assetController.py

@DanielJMaher 
This should fix the issue

Add else if to uframe asset search to prevent duplicate object in list

---

ooiservices/app/main/alertsalarms.py
ooiservices/app/main/notifications.py
ooiservices/app/main/user_event_notification.py
ooiservices/app/models.py
ooiservices/tests/test_alert_alarm.py
ooiservices/tests/test_notifications.py
ooiservices/tests/test_user_event_notifications.py

added modifications/updates for alerts and alarms.

Updates and modifications for alerts and alarms.

---

ooiservices/app/uframe/plot_tools.py
ooiservices/app/uframe/plotting.py

@birdage @DanielJMaher please review

Fix quiver plot arrows

---

ooiservices/app/config.yml
ooiservices/app/main/user.py

@DanielJMaher 
This should be ready to go.
Note there is a new config Key under LOCAL_DEVELOPMENT called TOEMAIL
This is used to set a email:to when testing emails on local.
If you have a local debug please add this key there

Send email when account goes from inactive to active

---

ooiservices/app/main/routes.py
ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/controller.py

@DanielJMaher , @oceanzus , Please review the search method for streams and assets

improved searching for logical 'and' results

---

ooiservices/app/config.yml
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

@DanielJMaher @birdage please review

Add better error logging and increase timeout

---

ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/controller.py

@oceanzus , @DanielJMaher , @c0mster   Please review!

Support for sorting in UI

---

ooiservices/app/uframe/plotting.py

Skinny quiver arrows and better label

---

ooiservices/app/redmine/routes.py

@DanielJMaher this goes with a UI PR, hold off a sec

Update redmine create ticket

---

ooiservices/app/main/annotation.py

<b>do not merge yet</b>
@DanielJMaher FYI

update annotation service connection

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py
ooiservices/app/uframe/plot_tools.py
ooiservices/app/uframe/plotting.py

@DanielJMaher @birdage 
Add the stacked time series plot. Goes with https://github.com/asascience-open/ooi-ui/pull/489

Stacked ts plot

---

ooiservices/app/main/alertsalarms.py
ooiservices/app/uframe/assets.py

@DanielJMaher @FBRTMaka review pls...should affect anything

add support for status in services

---

ooiservices/app/uframe/assets.py
ooiservices/app/uframe/controller.py

@DanielJMaher , @birdage , @Bobfrat , could anyone review when possible?

Fixed issue with TOC flattening. improved error checking.

---

ooiservices/app/main/alertsalarms.py

fix function request

---

ooiservices/app/main/alertsalarms.py

@DanielJMaher goes with https://github.com/asascience-open/ooi-ui/pull/509

update A/A for status

---

ooiservices/app/uframe/controller.py

@DanielJMaher @birdage 
The download endpoints had to be updated to comply with UFrame's new download capabilities.
#hacktober

Update download endpoints

---

ooiservices/app/main/alertsalarms.py

@FBRTMaka as discussed.
@ednad  @DanielJMaher this is the case for when an asset does not exist in the asset list for an A/A definition exists

small update for unknown assets

---

ooiservices/app/uframe/controller.py

@birdage , here's the updated file with the caching enabled.  We should close that other PR in lieu of this one.

Glider updates

---

ooiservices/app/uframe/assets.py

@birdage , along with other improvements, this will still allow the deployment events to show up (required for the map).

new arg to retain deployment events for minified asset responses

---

ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/tests/test_models.py

Relates to https://github.com/asascience-open/ooi-ui/pull/533

Adds opt-in for OOI email notices.

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

@DanielJMaher FYI, I will be working on the front end next
@birdage @FBRTMaka please review/merge

Add service endpoints for multistream plotting

---

ooiservices/app/__init__.py
ooiservices/app/alfresco/__init__.py
ooiservices/app/alfresco/errors.py
ooiservices/app/alfresco/routes.py
ooiservices/app/alfresco/tasks.py
ooiservices/app/alfresco/utils.py
ooiservices/app/config.yml
ooiservices/requirements/common.txt
ooiservices/tests/test_alfresco.py
ooiservices/tests/test_cmislib.py

@DanielJMaher , @birdage , @Bobfrat this is ready for review - should be good for the backend.  No need to wait on the front end.

Mc alfresco

---

ooiservices/app/main/operator_event.py
ooiservices/tests/test_log_entries.py

Service changes for oplog searching 
@DanielJMaher Please have tested to make sure I didn't miss/break something
Thanks

OpLog search Functionality

---

ooiservices/app/main/alertsalarms.py
ooiservices/app/main/notifications.py
ooiservices/app/models.py
ooiservices/tests/test_alert_alarm.py

@bridage relates to https://github.com/asascience-open/ooi-ui/pull/524

Adds ack and clear all methods for A&A.

---

ooiservices/app/uframe/controller.py

DO NOT MERGE... on pain of death!

uframe fix

---

ooiservices/app/uframe/controller.py

Reverts asascience-open/ooi-ui-services#409

Revert "uframe fix"

---

ooiservices/app/uframe/controller.py

@Bobfrat DO NOT MERGE ON PAIN OF DOUBLE DEATH

fix controller

---

ooiservices/app/uframe/controller.py

merge #411 first please...on pain of death.....

Fix download links

---

ooiservices/app/config.yml
ooiservices/app/json/sampleAntelopeResponse.json
ooiservices/app/uframe/controller.py

@DanielJMaher @birdage @FBRTMaka 
Mock service (for now) for acoustic data.
Goes with https://github.com/asascience-open/ooi-ui/pull/559

Mock service for acoustic data

---

ooiservices/app/config.yml
ooiservices/app/uframe/controller.py

@DanielJMaher @FBRTMaka please review/merge

Update antelope endpoint and enable sorting

---

db/ooiui_schema_data.sql
ooiservices/app/main/routes.py
ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/assets.py
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/events.py

@DanielJMaher fixes a bug in searching, and adds keys for stream name translations.

stream name translation updates

---

ooiservices/app/uframe/assets.py
ooiservices/app/uframe/controller.py

roll back the hiding of eng insturments

---

ooiservices/manage.py

fixes for deploying on linux distros

---

ooiservices/app/__init__.py
ooiservices/app/uframe/events.py
ooiservices/requirements/common.txt

…or cache to be shared across multiple worker instances
@asascience-open/team-ooi-ui 
Hopefully this reaches everyone!  This VERY simple change will require a small workflow update.  You'll need to start 1 more process (yes, another window) for redis.  If you already use redis, then this will 'just work'!
Basically, after you update your requirements you can start the redis server by issuing the command (from the virtual env):
redis-server
Then, just set it aside.  Now, the ooi services will use that for cache which will eliminate the whole problem of 'warming up the cache' every time something changes.

HOTFIX for deployment

---

ooiservices/app/__init__.py
ooiservices/app/config.yml
ooiservices/app/tasks.py
ooiservices/app/uframe/UFrameAssetsCollection.py
ooiservices/app/uframe/UFrameEventsCollection.py
ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/assets.py
ooiservices/app/uframe/controller.py

@oceanzus This will start using the redis / celery services
@DanielJMaher we'll be able to sort the asset management page based on deployment type (PAST or PRESENT) which seems like a easy and BIG win.
@asascience-open/team-ooi-ui , make sure you get your redis / celery worked out!!

fixes to the asset CRUD and refactor

---

ooiservices/app/config.yml
ooiservices/app/uframe/__init__.py
ooiservices/app/uframe/subscribe.py

subscribe NOW

---

ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/events.py

Now returns all events that belong to a specific ref des

update events endpoint

---

ooiservices/app/main/c2_mission.py

@DanielJMaher @FBRTMaka Please review.

Adds mission executive and load functionality.

---

ooiservices/app/__init__.py
ooiservices/app/config.yml
ooiservices/app/main/alertsalarms.py

Adds REDIS_URL config var to init.

Adds query to support new triggered A&A display.

---

ooiservices/app/alfresco/routes.py
ooiservices/app/alfresco/utils.py
ooiservices/app/config.yml

@DanielJMaher @FBRTMaka REQUIRES CONFIG UPDATE!!!

Cruise docs

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

@DanielJMaher, @FBRTMaka 
Also add pretty title and subtitles.

Fix bug in interp plot request

---

ooiservices/app/uframe/assets.py
ooiservices/app/uframe/events.py

Mc permissions

---

ooiservices/app/celeryconfig.py

change the glider track update to every 8 hours

---

ooiservices/app/config.yml
ooiservices/app/main/authentication.py
ooiservices/app/main/oauth.py
ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/requirements/common.txt

@oceanzus @DanielJMaher 
Supporting PR for the cilogon

Mc ci logon

---

ooiservices/app/main/oauth.py

redirect to pretty ooi cilogon page

---

ooiservices/app/main/alertsalarms.py

@FBRTMaka as discussed, checks for ref_des

add checks for no ref_des

---

db/ooiui_vocab.sql
ooiservices/app/main/routes.py
ooiservices/app/models.py
ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/controller.py
ooiservices/manage.py
ooiservices/tests/test_routes.py

@oceanzus , @birdage , @Bobfrat , @ednad , @DanielJMaher 
Hey all, I made some significant changes to how the asset names are interpreted based on the reference designators.
@oceanzus , @ednad  I created a separate sql file that will load to a new table via the manage.py file.  I'm not married to this implementation, so if you need/want to make any changes let me know and I can update that.
@Bobfrat , @birdage, at this point it's really a consistency check and an exercise of rebuilding the DB with this new data.  We should get together today if possible to work out what need to do to keep the UI happy.
@birdage , lets look in detail at line 115 of routes.py and if we need to keep that or off load that hack to be on uframes plate instead.
Let me know if you need a hand setting it back up!

new vocab updates

---

ooiservices/app/alfresco/routes.py
ooiservices/app/celeryconfig.py

@DanielJMaher ,  This is a document that couldn't be found.  Adding a catch to handle a CMIS exception to return a 404 instead of a 500

proper error response for a document not found:

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data.py

@DanielJMaher @FBRTMaka 
Improved error handling/messages for getting plot data

Add better error messages

---

ooiservices/app/config.yml
ooiservices/app/main/user.py
ooiservices/app/redmine/routes.py
ooiservices/tests/test_user.py

Fixes tests.
@FBRTMaka @DanielJMaher Please review.

Fixes Redmine tracker_id lookup for ticket creation.

---

ooiservices/app/__init__.py
ooiservices/app/config.yml
ooiservices/app/main/authentication.py
ooiservices/app/models.py
ooiservices/manage.py
ooiservices/requirements/common.txt
ooiservices/tests/test_user.py

@FBRTMaka @DanielJMaher Please review and test.
These modifications allow for the management of the users via Flask-Admin and Flask-Security in a separate Flask app that will be rolled out early next week under a new repo.  We should perform a design review of the role/scope system in light of the new capability this provides and see if it will make the permission system a bit more intuitive to the OOI team.
As it is, these modifications stand on their own without the 'admin' app.

Adds Flask-Security password and role handling.

---

.travis.yml
ooiservices/app/celeryconfig.py
ooiservices/app/tasks.py
ooiservices/app/uframe/controller.py
ooiservices/tests/test_large_file_formats.py

@FBRTMaka @DanielJMaher please review

Fetch Large Format Data

---

ooiservices/requirements/common.txt

@DanielJMaher @oceanzus @Bobfrat @FBRTMaka you need 0.3.2 NOT 0.2.7, otherwise login does NOT WORK!!!

urgent fix for requirements file

---

ooiservices/manage.py

@DanielJMaher @FBRTMaka Urgent review please.

Fixes save_users=True model change issues.

---

ooiservices/app/tasks.py
ooiservices/app/uframe/controller.py

@DanielJMaher on hold for now, but works as desired 
TODO

Update to glider processing

---

ooiservices/app/models.py
ooiservices/app/uframe/controller.py

@DanielJMaher , @oceanzus new model for a table in the DB where we store the list of disabled streams.
Will need a DB rebuild . . .

Mc data manager page

---

ooiservices/manage.py

@DanielJMaher @FBRTMaka Please review while I test on uframe.ooi

Adds --save_disabled_streams option to rebuild_schema

---

ooiservices/app/config.yml

ANnotate config to help deployment

---

ooiservices/app/uframe/controller.py

@DanielJMaher , this will get the page loading again. Simple error checking is all that is done here.

fixes the glider error

---

db/ooiui_vocab.sql

@DanielJMaher @FBRTMaka Please review and merge this minor change.

Fixes minor spelling error.

---

ooiservices/app/uframe/controller.py

@bnfish , @DanielJMaher 
Hey Ben,
This will support the work you did on the front end.  If you'd like to test it out have a go at it!  
Next steps are to spruce up that 'control bar' at the top, but it's not a top priority.

Mc date range slider

---

ooiservices/app/uframe/controller.py

Fixes High BW function and makes it dynamic

---

ooiservices/app/__init__.py
ooiservices/app/celeryconfig.py
ooiservices/app/config.yml
ooiservices/app/main/authentication.py
ooiservices/app/main/c2.py
ooiservices/app/main/c2_direct_access.py
ooiservices/app/main/routes.py
ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/app/tasks.py
ooiservices/app/uframe/__init__.py
ooiservices/app/uframe/assetController.py
ooiservices/app/uframe/assets.py
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/vocab.py
ooiservices/requirements/common.txt
ooiservices/tests/test_routes.py

User management, asset and vocabulary support added.

---

ooiservices/app/main/alertsalarms.py
ooiservices/app/main/arrays.py
ooiservices/app/main/instrument_deployment.py
ooiservices/app/main/operator_event.py
ooiservices/app/main/user_event_notification.py
ooiservices/app/uframe/controller.py
ooiservices/tests/test_arrays.py
ooiservices/tests/test_instrument_deployments.py
ooiservices/tests/test_log_entries.py

Fixes Permissions Mapping

---

ooiservices/app/uframe/data.py

@oceanzus I've already had this on uFrame and confirm it works.  Checked Feather plots as well.  Should be safe.

Fixes Binned Plots

---

ooiservices/app/uframe/controller.py

@DanielJMaher Please review and merge ASAP for the win!

Improves parameter stream names.

---

ooiservices/app/main/user.py

Logging of scope changes

---

ooiservices/app/uframe/plotting.py

fix title and y label

---

ooiservices/app/m2m/routes.py
ooiservices/app/main/user.py
ooiservices/app/models.py
ooiservices/manage.py
ooiservices/tests/test_models.py

Adds user-who-changed scope and API token to log file.

Adds M2M API token support.

---

ooiservices/app/uframe/controller.py

Updates get_uframe_plot_contents_chunked.

Fixes import statements mistake from previous PR.

---

ooiservices/app/uframe/controller.py
ooiservices/app/uframe/cruise_tools.py

Fixes get_events_by_ref_des method missing error.

Fixes cruises not displaying.

---

ooiservices/app/uframe/controller.py

@oceanzus uFrame now requires a "user" field for all Synch requests.  This fixes plotting.

Sends User to uFrame when plotting

---

ooiservices/app/uframe/controller.py

Fixes typo that had broken some plotting routines.

Fixes a typo in plotting

---

ooiservices/app/uframe/asset_tools.py

This fixes the issue with assets appearing at -1/-1

Interim Patch to fix Lat/Lon issues

---

ooiservices/app/uframe/plot_tools.py
ooiservices/app/uframe/plotting.py

@DanielJMaher @oceanzus 
Please review. Added some pep8 formatting as well

Update stacked timeseries and 3d scatter plots

---

ooiservices/app/uframe/controller.py

@DanielJMaher @ednad This is a critical fix required for plotting.  Please review and merge soonest.

Adds execDPA flag to data requests for plotting from uframe.

---

.gitignore
ooiservices/app/main/user.py
ooiservices/app/models.py

Adds audit table to database for logging events.
Updates .gitignore to ignore Thumbs.db

Adds Audit Log

---

ooiservices/app/config.yml
ooiservices/app/m2m/help_data_12576.py
ooiservices/app/m2m/help_tools.py
ooiservices/app/m2m/routes.py
ooiservices/app/main/annotation.py
ooiservices/app/uframe/__init__.py
ooiservices/app/uframe/common_tools.py
ooiservices/app/uframe/config.py
ooiservices/app/uframe/controller.py
ooiservices/app/uframe/data_availability.py
ooiservices/app/uframe/events.py
ooiservices/app/uframe/uframe_tools.py

Sprint 9 Release

---

ooiservices/app/m2m/routes.py
ooiservices/app/uframe/data_availability.py

Fixes minor data availability color bug.

Adds authenticated user to M2M ingest request.

---

ooiservices/app/uframe/controller.py

Fixes estimate_only url parameter pass through to uframe.

---

ooiservices/app/main/sys.py
ooiservices/app/uframe/controller.py

Adds route to post redis key, value and ttl.

Fixes route security. (14492)

---

ooiservices/app/main/alertsalarms.py
ooiservices/app/main/authentication.py
ooiservices/app/main/c2_direct_access.py
ooiservices/app/main/oauth.py
ooiservices/app/models.py
ooiservices/app/uframe/assets.py
ooiservices/app/uframe/assets_create_update.py
ooiservices/app/uframe/deployment_tools.py
ooiservices/app/uframe/deployments_create_update.py
ooiservices/app/uframe/stream_tools.py
ooiservices/app/uframe/stream_tools_iris.py
ooiservices/app/uframe/uframe_tools.py
ooiservices/tests/test_alert_alarm.py

-Data Catalog: Fixes double entries for HYDLF instruments. (14696)
-Data Catalog: Asset management and deployment editing fixes. (14443)
-Data Catalog: Plots returning images width fix. (14714)
-General: CI Logon update. (14697)

Updates and fixes for v1.9.0

---

ooiservices/app/uframe/stream_tools.py
ooiservices/app/uframe/vocab.py

Data Catalog: Fixes platform and instrument filters. (14742)
Data Catalog: Changes parameter standard name to contents of netcdf_name. (14737)
Media: Fixes broken elemental reference. (14757)

Version 1.9.1

---

ooiservices/app/main/annotation.py
ooiservices/requirements/common.txt

Bumps Pillow to 8.3.2
Bumps flask-cors to 3.0.9
Bumps py to 1.10.10

Removes begin and end times from annotation request.
